import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Roboto} from 'next/font/google';
import Navbar from "../components/Navbar";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const getRoboto=Roboto({
  subsets:['greek-ext'],
  display:'swap',
  variable:'--font-Roboto',
  weight:'400'

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense>
      <body
        className={`${geistSans.variable} ${geistMono.variable}${getRoboto.variable} antialiased`}
      >
        <Navbar/>
        <main className="mt-20 bg-gradient-to-r from-[#e2e6e8] to-[#f4faf9] w-full h-full">
        {children}

        </main>
      </body>             
      </Suspense>
    </html>
  );
}
